config/routes.rb
Rails.application.routes.draw do
 	resources :notes do
    collection do
      get :search
    end
  end

 	devise_for :users

 	resources :users, only: [:show, :edit, :update] do
 		member do
      get :notes
 			get :like_notes
      get :following
      get :follower
 		end
 	end

  root 'home#top'

  get '/about' => 'home#about'

	post '/like/:note_id' => 'likes#like', as: 'like'

	delete '/unlike/:note_id' => 'likes#unlike', as: 'unlike'

  post '/follow/:user_id' => 'follow#follow', as: 'follow'
  delete '/unfollow/:user_id' => 'follow#unfollow', as: 'unfollow'

  post '/comments/:id' => 'comments#create', as: 'comments'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  
  belongs_to :user
  belongs_to :note
end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :note
end

app/models/note.rb
class Note < ApplicationRecord
	validates :image, presence:true
	validates :category, presence:true
	validates :content, presence:true
	validates :user_id, presence:true

	belongs_to :user
	has_many :likes, dependent: :destroy

  has_many :comments, dependent: :destroy
  has_many :comment_users, through: :comments, source: :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :target, class_name: "User"
  belongs_to :from, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  has_many :notes, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_notes, through: :likes, source: :note

  has_many :active_relationships, class_name: "Relationship", foreign_key: "from_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "target_id", dependent: :destroy
   #フォローしている対象の集合体
  has_many :following_users, through: :active_relationships, source: :target
   #フォロワーの集合体
  has_many :followers, through: :passive_relationships, source: :from

  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  #devise機能で最初からあるもの（id,emailなど）以外で、後からカラムに追加したものは以下の記述でカラム更新できるようにする。:acount_updateの部分はapp/controllers/devise/registrations_controller.rbを見る（ただし、Deviseをインストールしてもそのコントローラは生成されません。Deviseが内部的に持っているコントローラが使用されます。そのため、Deviseのコントローラの挙動を変えたい場合は、そのDeviseのコントローラクラスを継承した独自のコントローラを作成する必要があります。）
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create

    note = Note.find(params[:id])
    comment = current_user.comments.build(note_id: note.id)
    comment.content = params[:comment][:content]
    comment.save
    if comment.save
      redirect_to note, notice: 'コメントを投稿しました！'
    else
      redirect_to note, notice: 'コメントを入力してください。'
    end
  end

end

app/controllers/follow_controller.rb
class FollowController < ApplicationController

  def follow
    target = User.find(params[:user_id])
    active_relationships = current_user.active_relationships.build(target_id: target.id)
    active_relationships.save
    redirect_to target
  end
  
  def unfollow
    target = User.find(params[:user_id])
    active_relationships = current_user.active_relationships.find_by(target_id: target.id)
    active_relationships.destroy
    redirect_to target
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  	@notes = Note.all.order(created_at: :desc)
  end
 

  def about
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def like
		note = Note.find(params[:note_id])
    like = current_user.likes.build(note_id: note.id)
    like.save
    redirect_to note
	end

	def unlike
		note = Note.find(params[:note_id])
		like = current_user.likes.find_by(note_id: note.id)
		like.destroy
		redirect_to note
	end

	
	
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update] 

  
  # GET /notes/1
  # GET /notes/1.json
  def show
    @comment = Comment.new
    @comments = @note.comments.order(created_at: :desc)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(note_params)
    file = params[:note][:image]
    if !file.nil?
      file_name = file.original_filename
      File.open("public/note_images/#{file_name}", 'wb'){|f| f.write(file.read)}
      @note.image = file_name
    end
    if @note.save
      redirect_to @note, notice: '投稿しました！'
    else
      render :new
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: '更新しました！' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    redirect_to current_user, notice: '削除しました'
  end

  def search
    @category_title = params[:category]
    @notes = Note.where(category: @category_title).order(created_at: :desc)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:category, :content)
    end

    def correct_user
      note = Note.find(params[:id])
      if current_user.id != note.user.id
        redirect_to root_path, alert: '許可されていないページです'
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
  before_action :correct_user, only: [ :edit, :update]
  before_action :set_user, only: [ :show, :edit, :update, :notes, :like_notes, :following, :follower ]


  def show
    @notes = @user.notes.order(created_at: :desc)
    @title = "投稿"
    @categories = Category.all
    @following_users = @user.following_users
    @following_notes = Note.where("user_id IN (?) OR user_id = ?", @user.following_users.map(&:id), @user.id).order(created_at: :desc)
  end


  def edit
  end

  def create
  end

  def update
    if  @user.update(user_params)
      redirect_to @user, notice: 'プロフィールが更新されました'
    else
      render :edit
    end
  end

  def following
    @following_users = @user.following_users.order(created_at: :desc)
  end

  def follower
    @followers = @user.followers.order(created_at: :desc)
  end

  def notes
    @title = "投稿"
    @notes = @user.notes.order(created_at: :desc)
  end

  def like_notes
    @notes = @user.like_notes.order(created_at: :desc)
    @title = "お気に入り"
    @categories = Category.all
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :introduction)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def correct_user
      user = User.find(params[:id])
      if current_user.id != user.id
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about">


	<h1>Pettaでできること</h1>

	<section>
		<h2>ペットを飼っている人</h2>
		
		<h3>自慢のペットの写真をカテゴリーごとに保存できます</h3>
		<p>日常生活からおでかけした時の思い出、病気やケガをしたときのことなどもカテゴリーごとに記録できます。</p>

		<h3>あなたの経験がだれかの役に立ちます</h3>
		<p>あなたとペットの経験を記録することで、ペットのことで悩んでいる人や、ペットを飼おうか悩んでいる人の参考となります。多くの動物が幸せになれるよう、自分の経験をたくさん共有しましょう！</p>	
	</section>

	<section>
		<h2>動物が好きな人</h2>

		<h3>可愛いペットに癒される</h3>
		<p>Pettaはペットを飼っていなくても利用できます。気に入った投稿はお気に入りすればいつでも見ることができます。</p>
		
		<h3>ペット飼育への知見を深められる</h3>
		<p>ペットの飼育は楽しいことばかりではなく、動物を幸せにするだけの正しい知識や経済力などが求められます。Pettaでは、動物の可愛い姿だけではなく、ペット飼育をする上で知っておきたい事が広く共有されるように努めます。</p>
		<p>いつかペットを飼いたい人も、みんなの投稿を見て動物に対する知見を深めておきましょう。</p>
	</section>

	
</div>

app/views/home/category.html.erb
<p><strong><%= @category_title %></strong><%="の検索結果" %></p>

<% @notes.each  do |note| %>
  <li>
    <%= link_to note, class: "note-card" do %>
      <%= image_tag "/note_images/#{note.image}", class: "note-image" %>
      <div class="note-category"><%= note.category %></div>
    <% end %>
  </li>
<% end %>

app/views/home/search.html.erb
<p><strong><%= @category %></strong><%="の検索結果" %></p>

<% @notes.each  do |note| %>
  <li>
    <%= link_to note, class: "note-card" do %>
      <%= image_tag "/note_images/#{note.image}", class: "note-image" %>
      <div class="note-category"><%= note.category %></div>
    <% end %>
  </li>
<% end %>

app/views/home/top.html.erb
<div class="search">
	<p>カテゴリーごとの検索</p>
	<div>
		<%= form_tag search_notes_path, method: 'get' do %> 
			<%= select_tag :category, options_from_collection_for_select(Category.all,:title,:title) %>
			<input type="submit" value="検索" >
		<% end %>
	</div>
</div>



<% @notes.each do |note| %>
	<li>
		<%= link_to note, class: "top-note-card" do %>
			<%= image_tag "/note_images/#{note.image}", class: "note-image" %>
			<div class="note-category top-note-category"><%= note.category %></div>
		<% end %>
	</li>
<% end %>

app/views/notes/_form.html.erb
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "エラー") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= f.label :画像 %></td>
      <td><%= f.file_field :image %></td>
    </tr>
    <tr>
      <td><%= f.label :カテゴリー %></td>
      <td><%= f.collection_select :category, Category.all, :title, :title %></td>
    </tr>
    <tr>
      <td><%= f.label :コメント %></td>
      <td><%= f.text_field :content %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit "投稿", data: { disable_with: '投稿中...' } %>
  </div>

<% end %>

app/views/notes/edit.html.erb
<h1>Noteを編集</h1>

<% note = @note %>
<%= form_for(note) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "エラー") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= f.label :カテゴリー %></td>
      <td><%= f.collection_select :category, Category.all, :title, :title %></td>
    </tr>
    <tr>
      <td><%= f.label :コメント %></td>
      <td><%= f.text_field :content %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit "更新" %>
  </div>

<% end %>


<%= link_to '戻る', @note %>

app/views/notes/new.html.erb
<h1>Noteを投稿しよう！</h1>

<%= render 'form', note: @note %>

<%= link_to 'マイページへ', user_path(current_user) %>

app/views/notes/search.html.erb
<p><strong><%= @category_title %></strong><%="の検索結果" %></p>

<% @notes.each  do |note| %>
  <li>
    <%= link_to note, class: "top-note-card" do %>
      <%= image_tag "/note_images/#{note.image}", class: "note-image" %>
    <% end %>
  </li>
<% end %>

app/views/notes/show.html.erb
<p><%= notice %></p>
<div class="note-container">
  <%= image_tag "/note_images/#{@note.image}", class: "note-image" %>

  <div class="note-info">
    <div><%= link_to "@"+@note.user.name, @note.user, class: "note-user" %></div>
    <div class="like-wrapper">
    <% if current_user.likes.find_by(note_id: @note.id) %>
      <%= link_to unlike_path(@note.id), method: :delete do %>
        <%= image_tag "red-heart.png" %>×<%= @note.likes.count %>
      <% end %>
    <% else %>
      <%= link_to like_path(@note.id), method: :post do %>
        <%= image_tag "gray-heart.png" %>×<%= @note.likes.count %>
      <% end %>
    <% end %>
  </div>
    <div class="note-category"><%= @note.category %></div>
    <div class="note-content"><%= @note.content %></div>
  </div>

  

  <% @comments.each do |comment| %>
    <div class="comment">
      <div class="comment-user-name"><%= link_to "@"+comment.user.name, user_path(comment.user.id) %></div>
      <div class="comment-content"><%= comment.content %></div>
    </div>  
  <% end %>

  
  <div class="comment-post">
      <%= form_for(@comment) do |f| %>
        <%= f.text_field :content %>
        <%= f.submit "コメントする", data: { disable_with: '投稿中...' } %>
      <% end %>
    </div>
  
</div>






<div>
 
</div>


      


<% if current_user == @note.user %>
  <%= link_to '編集', edit_note_path(@note) %> |
  <%= link_to "削除", note_path(@note), method: :delete %>
<%end%>

app/views/users/_notes.html.erb
<div class="user-contents-area">

<h1><%= @title %></h1>
<% @notes.each do |note| %>
	<li>
		<%= link_to note, class: "note-card" do %>
			<%= image_tag "/note_images/#{note.image}", class: "note-image" %>
		<% end %>
	</li>
<% end %>

</div>

app/views/users/_profile.html.erb
<div class="profile-area">
	<h1><%= link_to @user.name, @user, class: "name" %></h1>
  <% if current_user != @user %>
    <div>
      <% if current_user.active_relationships.find_by(target_id: @user.id) %>
        <%= link_to unfollow_path(@user.id), class: "follow-btn", method: :delete do %>
          <p>フォロー解除</p>
        <% end %>
      <% else %>
        <%= link_to follow_path(@user.id), class: "follow-btn", method: :post do %>
          <p>フォロー</p>
        <% end %>
      <% end %>
    </div>  
　<% end %>
  <div>
    <li>
    <%= link_to notes_user_path(@user.id) do %>
      投稿：<%= @user.notes.count %>
    <% end %>
    </li>
    <li>
    <%= link_to following_user_path(@user.id) do %>
      フォロー：<%= @user.active_relationships.count %>
    <% end %>
    </li>
    <li>
    <%= link_to follower_user_path(@user.id) do %>
      フォロワー：<%= @user.passive_relationships.count %>
    <% end %>
    </li>
  </div>
	<div class="introduction-area"><%= @user.introduction %></div>
	<div><%= link_to "#{@user.likes.count}個のお気に入り", like_notes_user_path(@user.id), class: "fav-link" %></div>
	<div class="edit-prof-btn-container">
		<% if current_user.id == @user.id %>
			<div><%= link_to 'プロフィールを編集', edit_user_path(@user), class: "edit-prof-btn" %></div>
		<% end %>
	</div>
</div>

app/views/users/edit.html.erb
<h1>プロフィールを編集</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <p><%= @user.errors.count %>件のエラーがあります。</p>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>名前</td>
      <td><%= f.text_field :name, class: "form-control name-field" %></td>
    </tr>
    <tr>
      <td>自己紹介</td>
      <td><%= f.text_field :introduction, class: "form-control name-field" %></td>
    </tr>
    <tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= f.text_field :email, class: "form-control email-field" %></td>
    </tr>
    <tr>
      <td><%= f.submit '保存', class: "btn" %></td>
    </tr>
  </table>

  <p><%= link_to 'アカウント設定', edit_user_registration_path %></p>

<%= link_to "戻る", :back %>

<% end %>

app/views/users/follower.html.erb
<%= render 'profile' %>

<div class="user-contents-area">
  <h1>フォロワー</h1>
  <div>
    <% @followers.each do |follower| %>
      <p><%= link_to follower.name, follower %></p>
    <% end %>
  </div>
</div>

app/views/users/following.html.erb
<%= render 'profile' %>

<div class="user-contents-area">
  <h1>フォロー</h1>
  <div>
    <% @following_users.each do |following| %>
      <p><%= link_to following.name, following %></p>
    <% end %>
  </div>
</div>

app/views/users/like_notes.html.erb
<%= render 'profile' %>


<%= render 'notes' %>

app/views/users/notes.html.erb
<%= render 'profile' %>


<%= render 'notes' %>

app/views/users/show.html.erb
<%= render 'profile' %>


<% if current_user == @user %>
	<div class="user-contents-area">		
	  <% @following_notes.each do |note| %>
	    <li>
	      <%= link_to note, class: "note-card" do %>
	      	<div><%= note.user.name %></div>
	        <%= image_tag "/note_images/#{note.image}", class: "note-image" %>
	      <% end %>
	    </li>
	  <% end %>
	</div>
<% end %>

<% if current_user != @user %>

	
<%= render 'notes'%>

	
		
<% end %>